/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_OutputSettingsBroadcastReceiver */

#ifndef _Included_utils_jni
#define _Included_utils_jni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_dbstar_app_media_GDPlayerUtil
 * Method:    writeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dbstar_app_media_GDPlayerUtil_writeFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
