/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_OutputSettingsBroadcastReceiver */

#ifndef _Included_utils_jni
#define _Included_utils_jni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_dbstar_util_NativeUtil
 * Method:    writeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dbstar_util_NativeUtil_writeFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dbstar_util_NativeUtil
 * Method:    writeFile
 * Signature: (Ljava/lang/String)I
 */
JNIEXPORT jint JNICALL Java_com_dbstar_util_NativeUtil_runSystem
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
