LOCAL_PATH := $(call my-dir)


include $(CLEAR_VARS)

LOCAL_SRC_FILES               := \
	NativeFormats/main.cpp \
	NativeFormats/JavaNativeFormatPlugin.cpp \
	NativeFormats/JavaPluginCollection.cpp \
	NativeFormats/util/AndroidUtil.cpp \
	NativeFormats/util/JniEnvelope.cpp \
	NativeFormats/zlibrary/core/src/constants/ZLXMLNamespace.cpp \
	NativeFormats/zlibrary/core/src/encoding/DummyEncodingConverter.cpp \
	NativeFormats/zlibrary/core/src/encoding/Utf16EncodingConverters.cpp \
	NativeFormats/zlibrary/core/src/encoding/Utf8EncodingConverter.cpp \
	NativeFormats/zlibrary/core/src/encoding/JavaEncodingConverter.cpp \
	NativeFormats/zlibrary/core/src/encoding/ZLEncodingCollection.cpp \
	NativeFormats/zlibrary/core/src/encoding/ZLEncodingConverter.cpp \
	NativeFormats/zlibrary/core/src/filesystem/ZLDir.cpp \
	NativeFormats/zlibrary/core/src/filesystem/ZLFSManager.cpp \
	NativeFormats/zlibrary/core/src/filesystem/ZLFile.cpp \
	NativeFormats/zlibrary/core/src/filesystem/ZLInputStreamDecorator.cpp \
	NativeFormats/zlibrary/core/src/filesystem/zip/ZLGzipInputStream.cpp \
	NativeFormats/zlibrary/core/src/filesystem/zip/ZLZDecompressor.cpp \
	NativeFormats/zlibrary/core/src/filesystem/zip/ZLZipDir.cpp \
	NativeFormats/zlibrary/core/src/filesystem/zip/ZLZipEntryCache.cpp \
	NativeFormats/zlibrary/core/src/filesystem/zip/ZLZipHeader.cpp \
	NativeFormats/zlibrary/core/src/filesystem/zip/ZLZipInputStream.cpp \
	NativeFormats/zlibrary/core/src/language/ZLCharSequence.cpp \
	NativeFormats/zlibrary/core/src/language/ZLLanguageDetector.cpp \
	NativeFormats/zlibrary/core/src/language/ZLLanguageList.cpp \
	NativeFormats/zlibrary/core/src/language/ZLLanguageMatcher.cpp \
	NativeFormats/zlibrary/core/src/language/ZLStatistics.cpp \
	NativeFormats/zlibrary/core/src/language/ZLStatisticsGenerator.cpp \
	NativeFormats/zlibrary/core/src/language/ZLStatisticsItem.cpp \
	NativeFormats/zlibrary/core/src/language/ZLStatisticsXMLReader.cpp \
	NativeFormats/zlibrary/core/src/library/ZLibrary.cpp \
	NativeFormats/zlibrary/core/src/logger/ZLLogger.cpp \
	NativeFormats/zlibrary/core/src/util/ZLFileUtil.cpp \
	NativeFormats/zlibrary/core/src/util/ZLStringUtil.cpp \
	NativeFormats/zlibrary/core/src/util/ZLUnicodeUtil.cpp \
	NativeFormats/zlibrary/core/src/xml/ZLAsynchronousInputStream.cpp \
	NativeFormats/zlibrary/core/src/xml/ZLPlainAsynchronousInputStream.cpp \
	NativeFormats/zlibrary/core/src/xml/ZLXMLReader.cpp \
	NativeFormats/zlibrary/core/src/xml/expat/ZLXMLReaderInternal.cpp \
	NativeFormats/zlibrary/core/src/unix/filesystem/ZLUnixFSDir.cpp \
	NativeFormats/zlibrary/core/src/unix/filesystem/ZLUnixFSManager.cpp \
	NativeFormats/zlibrary/core/src/unix/filesystem/ZLUnixFileInputStream.cpp \
	NativeFormats/zlibrary/core/src/unix/filesystem/ZLUnixFileOutputStream.cpp \
	NativeFormats/zlibrary/core/src/unix/library/ZLUnixLibrary.cpp \
	NativeFormats/zlibrary/text/src/model/ZLCachedMemoryAllocator.cpp \
	NativeFormats/zlibrary/text/src/model/ZLTextModel.cpp \
	NativeFormats/zlibrary/text/src/model/ZLTextParagraph.cpp \
	NativeFormats/zlibrary/ui/src/android/filesystem/JavaFSDir.cpp \
	NativeFormats/zlibrary/ui/src/android/filesystem/JavaInputStream.cpp \
	NativeFormats/zlibrary/ui/src/android/filesystem/ZLAndroidFSManager.cpp \
	NativeFormats/zlibrary/ui/src/android/library/ZLAndroidLibraryImplementation.cpp \
	NativeFormats/dbstarplayer/src/bookmodel/BookModel.cpp \
	NativeFormats/dbstarplayer/src/bookmodel/BookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/EncodedTextReader.cpp \
	NativeFormats/dbstarplayer/src/formats/FormatPlugin.cpp \
	NativeFormats/dbstarplayer/src/formats/PluginCollection.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2BookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2CoverReader.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2MetaInfoReader.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2Plugin.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2Reader.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2TagManager.cpp \
	NativeFormats/dbstarplayer/src/formats/fb2/FB2UidReader.cpp \
	NativeFormats/dbstarplayer/src/formats/css/StyleSheetParser.cpp \
	NativeFormats/dbstarplayer/src/formats/css/StyleSheetTable.cpp \
	NativeFormats/dbstarplayer/src/formats/html/HtmlBookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/html/HtmlDescriptionReader.cpp \
	NativeFormats/dbstarplayer/src/formats/html/HtmlEntityCollection.cpp \
	NativeFormats/dbstarplayer/src/formats/html/HtmlPlugin.cpp \
	NativeFormats/dbstarplayer/src/formats/html/HtmlReader.cpp \
	NativeFormats/dbstarplayer/src/formats/html/HtmlReaderStream.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/NCXReader.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/OEBBookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/OEBCoverReader.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/OEBMetaInfoReader.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/OEBPlugin.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/OEBTextStream.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/OEBUidReader.cpp \
	NativeFormats/dbstarplayer/src/formats/oeb/XHTMLImageFinder.cpp \
	NativeFormats/dbstarplayer/src/formats/rtf/RtfBookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/rtf/RtfDescriptionReader.cpp \
	NativeFormats/dbstarplayer/src/formats/rtf/RtfPlugin.cpp \
	NativeFormats/dbstarplayer/src/formats/rtf/RtfReader.cpp \
	NativeFormats/dbstarplayer/src/formats/rtf/RtfReaderStream.cpp \
	NativeFormats/dbstarplayer/src/formats/txt/PlainTextFormat.cpp \
	NativeFormats/dbstarplayer/src/formats/txt/TxtBookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/txt/TxtPlugin.cpp \
	NativeFormats/dbstarplayer/src/formats/txt/TxtReader.cpp \
	NativeFormats/dbstarplayer/src/formats/util/EntityFilesCollector.cpp \
	NativeFormats/dbstarplayer/src/formats/util/MergedStream.cpp \
	NativeFormats/dbstarplayer/src/formats/util/MiscUtil.cpp \
	NativeFormats/dbstarplayer/src/formats/util/XMLTextStream.cpp \
	NativeFormats/dbstarplayer/src/formats/xhtml/XHTMLReader.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/DocBookReader.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/DocMetaInfoReader.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/DocPlugin.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/DocStreams.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/OleMainStream.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/OleStorage.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/OleStream.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/OleStreamParser.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/OleStreamReader.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/OleUtil.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/DocInlineImageReader.cpp \
	NativeFormats/dbstarplayer/src/formats/doc/DocFloatImageReader.cpp \
	NativeFormats/dbstarplayer/src/library/Author.cpp \
	NativeFormats/dbstarplayer/src/library/Book.cpp \
	NativeFormats/dbstarplayer/src/library/Comparators.cpp \
	NativeFormats/dbstarplayer/src/library/Library.cpp \
	NativeFormats/dbstarplayer/src/library/Tag.cpp \
	NativeFormats/dbstarplayer/src/library/UID.cpp

LOCAL_C_INCLUDES              := \
	$(LOCAL_PATH)/NativeFormats/util \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/constants \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/encoding \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/filesystem \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/image \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/language \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/library \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/logger \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/util \
	$(LOCAL_PATH)/NativeFormats/zlibrary/core/src/xml \
	$(LOCAL_PATH)/NativeFormats/zlibrary/text/src/model

include $(BUILD_SHARED_LIBRARY)
